### ISSUE TITLE
Error: Bad Request

### ISSUE THREAD

**Issue by pdmcharms** [bcomnes/deploy-to-neocities#90] opened 2022-07-07 21:25 UTC
Hi, so I've been tweaking [my repository](https://github.com/pdmcharms/digitalseas-neocities) for the past few hours trying to deploy my site. Everything seems to go smoothly until trying to deploy when I receive a `Error: Bad Request` error. I know now it's because I'm trying to upload my entire repository, so I've tried to keep everything in a subfolder but I'm still not sure if I'm doing everything correctly.
Earlier I had made a `/public` folder that I assume `dist_dir` would read to carry my main website folders, like the actual `/public` - that holds my css, js, imgs - and `/views` folder that holds my site layout and pages, since I mainly made my site with EJS. I thought maybe the redundancy in the names were the issue, so I changed the main `/public` folder to `/website` and changed the `dist_dir` accordingly. Nothing worked, still the same error.

I don't know what to do, I'm not sure if maybe EJS is an issue? This is my first time really using GitHub so I'm still new to all of this.

**Comment by bcomnes** [comment] 2022-07-08 17:00
It looks like you have an express app in that repo. Neocities only hosts static assets and websites. Express apps require you host a live node process on a server, such as a VPS or heroku style host. You would need to convert your website to a fully static website before it can be deployed to neocities. 

Heroku and fly.io offer free hosting for websites that need a server process. Fly.io offers custom domains on their free tier as well.

If you really wanted to use neocities, you would need to pick a static site generator like https://www.11ty.dev or https://nextjs.org/docs/advanced-features/static-html-export (but be sure to stick with pure static builds if you go the next route). You can also could write your own static site generator (they are easy to build) if you wanted, but it sounds like you are still learning so you might get more mileage out of using an existing site generator.

**Comment by pdmcharms** [comment] 2022-07-08 21:35
Ah, I see! I had a hunch it might've been an issue with EJS not being compatible with Neocities but didn't understand how. I learned all of the stuff I do right now very quickly and wanted to exercise my skills somehow but am still very fuzzy on the why's and how's. Thank you for taking the time to explain this to me, I greatly appreciate it. I've used Heroku before but am instant on using Neocities because I like the community there, so I'll look into the site generators you recommended and figure out what I want to do. Thank you again.

**Comment by bcomnes** [comment] 2022-07-08 21:38
EJS is just a template library, you might be able to find a static site generator that uses it.

**Comment by bcomnes** [comment] 2022-07-12 00:58
Looks like thats the issue. Closing this for now, but we can reopen if you have further issues.  Good luck!

**Closed by bcomnes** 2022-07-12 00:58 UTC

**Comment by knassar702** [comment] 2022-08-10 12:44
hey @bcomnes,I've the same issue here with Hugo

here's my github action file: https://github.com/knassar702/knas.me/blob/master/.github/workflows/gh-pages.yml#L34

**Comment by bcomnes** [comment] 2022-08-10 15:21
Strange, looks like that action is hung. I would stop the job. It should not take 2 hours.

**Comment by knassar702** [comment] 2022-08-10 15:25
It stuck at 24% in the progress, also you can see the expected output of
hugo in gh-pages branch

**Comment by bcomnes** [comment] 2022-08-10 15:28
You should cancel the workflow, its probably hung in some kind of loop.

<img width="1840" alt="Screen Shot 2022-08-10 at 9 26 35 AM" src="https://user-images.githubusercontent.com/166301/183944417-840f4ca2-ff61-40bd-b419-daeabb6b9f7b.png">

**Comment by knassar702** [comment] 2022-08-10 15:31
I know how to cancel it and i did twice, I'm asking for a solution because I tried to re-run it with another hugo options and themes and It didn't work

**Comment by bcomnes** [comment] 2022-08-10 15:39
Ok, after finding a canceled run to see there error output (I can't see full output on a running action), Neocities API is returning this error:

```
Files to upload: 
    at async Promise.all (index 0)
    at NeocitiesAPIClient.deploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/webpack:/deploy-to-neocities/node_modules/async-neocities/index.js:346:1)
    at doDeploy (/home/runner/work/_actions/bcomnes/deploy-to-neocities/v1/webpack:/deploy-to-neocities/index.js:31:1) {
  status: 400,
  json: {
    result: 'error',
    error_type: 'invalid_file_type',
    message: 'main.css.map is not a valid file type (or contains not allowed content) for this site, files have not been uploaded'
  },
  results: [],
```

So something about that file is making neocities API unhappy. Map files are usually allowed so something about then content or encoding is not compatible with neocities. Fix this and you should be able to upload fine. 

With respect to the hung action, that looks like a bug. I'll have to look into it. First time seeing it.

**Comment by bcomnes** [comment] 2022-08-10 16:25
Ok, I fixed the hung run bug I think. v1.1.9 has the fix. I tried uploading your map file and it worked fine, so I'm not sure where the problem is. If you can isolate the problematic content, that would be the best place for me to find a fix.
